### PR TITLE
[MARXAN-2] catch-all exceptions filter

### PR DESCRIPTION
**Pull request by hotzevzl**
### Overview

Basic but hopefully effective catch-all exception filter.

Catches all uncaught exceptions that inherit from the base `Error` exception class.

Logs errors to logs.

In non-development environments, sends error code, message, request path and timestamp in API response for requests that trigger errors.

In development environments, also sends raw exception and stack trace 🚀 

I suppose we could avoid ever sending this info in the HTTP response and just log it. I'd keep it as is for now (it may help frontend devs to report issues without having to go and look at logs), and we can revisit later on.

### Designs

N/A

### Testing instructions

Send some malformed requests to random API endpoints (maybe easier if a POST one) - error details should show in the API logs and in the response.

### Feature relevant tickets

https://www.pivotaltracker.com/story/show/176865443

---

## Checklist before submitting

- [x] Meaningful commits and code rebased on `develop`.
- [ ] If this PR adds feature that should be tested for regressions when
      deploying to staging/production, please add brief testing instructions
      to the deploy checklist (`docs/deployment-checklist.md`)
- [x] Update CHANGELOG file

### CODE REVIEW

**Comment by hotzevzl** [comment]
@aagm I think this PR is ready for review (and to be merged once all looks fine) - I have rebased it on `develop` just now and tested it on a clean slate.

Given that we're sticking to JSON:API for error documents, we should start adding tests (for new features or adding to existing test sets whenever we have a chance to update them) that check for specific error codes, whenever we add these. In tests, we could parse these error payloads with the same package (`jsonapi-serializer`) we use for serializing stuff, I guess.

**Comment by hotzevzl** [comment]
@aagm I have put this back to draft status as I would like to work on e2e tests during my pairing sessions with Ibrahim. Maybe it would be a good idea to ask him to review the PR as well. I'll check with him, but I'll remove you as reviewer in the meanwhile.

**Comment by aagm** [comment]
Let me know when this is ready to review, i am eager to start using it :D

**Comment by aagm** [comment]
Worked as expected; only thing is that using the swagger to test it gives me a cors error on the call (but using the curl works as expected)

**Review by aagm — APPROVED** [review]

**Comment by hotzevzl** [comment]
> Worked as expected; only thing is that using the swagger to test it gives me a cors error on the call (but using the curl works as expected)

I should document the CORS settings... can you set the URL where you access the OpenAPI web UI to your `.env` in `NETWORK_CORS_ORIGINS` and see if that works ok?

`NETWORK_CORS_ORIGINS=http://localhost:3030` (and any more you may need, comma-separated)

**Pull request merged**
