### PR TITLE
User dropdown

### PR DESCRIPTION
**Pull request by mbarrenechea**
### Overview

This PR:
- remove popper to tippy for positioning use dropdown
- add some styles to that dropdown

### CODE REVIEW

**Review by pablopareja — CHANGES_REQUESTED** [review]
If you open the user tooltip and then click somewhere else in the interface the tooltip doesn't disappear 100%, there's still a thin horizontal border at the bottom that shows up for a few seconds. _See the screenshot attached below_

image

**Comment by mbarrenechea** [comment]
> If you open the user tooltip and then click somewhere else in the interface the tooltip doesn't disappear 100%, there's still a thin horizontal border at the bottom that shows up for a few seconds. _See the screenshot attached below_
> 
> image

Let me check

**Comment by mbarrenechea** [comment]
@pablopareja  I can't reproduce it

**Comment by mbarrenechea** [comment]
Merging despite @pablopareja 's issue

**Pull request merged**
