### PR TITLE
feat(api): protect api-events with api-key

### PR DESCRIPTION
**Pull request by kgajowy**
### Overview

It could be necessary to provide relevant envs on CI/staging/production

### Designs

_Link to the related design prototypes (if applicable)_

### Testing instructions

_Please explain how to test the PR: ID of a dataset, steps to reach the feature, etc._

### Feature relevant tickets

_Link to the related task manager tickets_

---

## Checklist before submitting

- [ ] Meaningful commits and code rebased on `develop`.
- [ ] If this PR adds feature that should be tested for regressions when
      deploying to staging/production, please add brief testing instructions
      to the deploy checklist (`docs/deployment-checklist.md`)
- [ ] Update CHANGELOG file

### CODE REVIEW

**Review by hotzevzl — APPROVED** [review]
@kgajowy thank you, looks great.

**Comment by hotzevzl** [comment]
actually, may it make sense to get this prop from env only once at app startup, rather than per-request in the guard?

**Comment by kgajowy** [comment]
> actually, may it make sense to get this prop from env only once at app startup, rather than per-request in the guard?

Could be, if we are fine to restart the deployed unit if we need to change the secret ;)

fixed in https://github.com/Vizzuality/marxan-cloud/pull/183/commits/700096169e0e73b90f090d90c402bfe14bc27708

**Comment by hotzevzl** [comment]
> > actually, may it make sense to get this prop from env only once at app startup, rather than per-request in the guard?
> 
> Could be, if we are fine to restart the deployed unit if we need to change the secret ;)
> 
> fixed in [7000961](https://github.com/Vizzuality/marxan-cloud/commit/700096169e0e73b90f090d90c402bfe14bc27708)

thanks, and yes, no problem in having to restart - this will rarely change in most cases.

**Pull request merged**
