### PR TITLE
feat(api): add service for cost surface template with queue management

### PR DESCRIPTION
**Pull request by Dyostiq**
### Overview

_Please write a description. If the PR is hard to understand, provide a quick explanation of the code._

### Designs

_Link to the related design prototypes (if applicable)_

### Testing instructions

_Please explain how to test the PR: ID of a dataset, steps to reach the feature, etc._

### Feature relevant tickets

_Link to the related task manager tickets_

---

## Checklist before submitting

- [ ] Meaningful commits and code rebased on `develop`.
- [ ] If this PR adds feature that should be tested for regressions when
      deploying to staging/production, please add brief testing instructions
      to the deploy checklist (`docs/deployment-checklist.md`)
- [ ] Update CHANGELOG file

### CODE REVIEW

**Review by kgajowy — APPROVED** [review]

**Comment by hotzevzl** [comment]
@Dyostiq thanks. Interfaces and tests look good.

I am not recognizing much of Kamil's recent work on queues here - I may be misunderstanding the intent, but I see a partial overlap and not much reuse: could we stick to the queue interfaces and workflow that Kamil has prepared (and used in some of the modules he's been working on)? If there are features missing or some interface mismatch with what is needed here, I'd suggest to try to update the existing Queues implementation,

**Comment by Dyostiq** [comment]
@hotzevzl

Hmm, actually the code here is using Kamil's QueueModule. The `BullmqQueue` implements specific needs of `QueuedCostTemplateService` and does not provide a universal abstraction. Kamil's module also does not do this. It keeps the queue management – creating the queue, unregistering it, etc., and I'm injecting the queue using the module's token. It's not very visible now because it's not brought together in the ScenariosModule, yet.

**Review by hotzevzl — APPROVED** [review]

**Comment by hotzevzl** [comment]
> @hotzevzl
> 
> Hmm, actually the code here is using Kamil's QueueModule. The `BullmqQueue` implements specific needs of `QueuedCostTemplateService` and does not provide a universal abstraction. Kamil's module also does not do this. It keeps the queue management – creating the queue, unregistering it, etc., and I'm injecting the queue using the module's token. It's not very visible now because it's not brought together in the ScenariosModule, yet.

yes, we need to converge on uniform structure and implementation details (for what is not really unique, of course) for these queue-based modules -- it seems we're still finding our way here, and that's fine at this stage, as long as we do some lightweight refactor once we've stabilised how we use these queues, to avoid having details differing across them, or every time a dev needs to make any changes they'd have to first orient themselves on what exactly to touch in each implementation, which is obviously not efficient.

**Comment by Dyostiq** [comment]
@hotzevzl differences between using queues (and using any other tool) are ok, because a dev may have specific needs (for example, here I use the specific nature of jobId). It's why I esteem the inversion – details are hidden behind an interface that expresses the needs of our class.  I try to avoid generalizing things too early to avoid creating a wrong abstraction. Then, it requires workarounds that bloat the code (and the code is not that expressive). As the rule of three says, with three very similar usages (adapters) we may generalize things.

**Comment by hotzevzl** [comment]
@Dyostiq I think we can merge this, right? feel free to do so if you don't need to apply any further changes

**Review by aagm — APPROVED** [review]

**Pull request closed without merging**
